require('dotenv').config();
const sequelize = require('../config/db');
const bcrypt = require('bcryptjs');
const { User, Category, Product, SiteSetting } = require('../models');

const seed = async () => {
  try {
    console.log('Starting seed...');

    const admin = await User.create({
      name: 'Admin Pandit Ji',
      email: 'admin@panditji.com',
      password: 'admin123',
      phone: '9999999999',
      role: 'admin',
    });
    console.log('Admin created:', admin.email);

    const customer = await User.create({
      name: 'Rahul Sharma',
      email: 'rahul@example.com',
      password: 'customer123',
      phone: '9876543210',
      role: 'customer',
    });
    console.log('Customer created:', customer.email);

    const createdCategories = await Category.bulkCreate([
      { name: 'Khade Masale', slug: 'whole-spices', description: 'Premium whole spices sourced directly from farms', displayOrder: 1 },
      { name: 'Dry Fruits', slug: 'dry-fruits', description: 'Premium quality dry fruits and nuts', displayOrder: 2 },
      { name: 'Pooja Samagri', slug: 'pooja-items', description: 'Items for religious ceremonies and daily worship', displayOrder: 3 },
    ]);
    console.log('Categories created');

    const catMap = {};
    createdCategories.forEach(cat => {
      catMap[cat.slug] = cat.id;
    });

    const products = await Product.bulkCreate([
      // --- KHADE MASALE ---
      {
        name: 'Sabut Kaali Mirch (Black Pepper Whole)',
        slug: 'sabut-kaali-mirch-whole',
        description: 'Premium Malabar black pepper corns. Sourced from the lush hills of Kerala, our black pepper offers a sharp, pungent aroma and deep heat.',
        shortDescription: 'Premium Malabar whole black pepper corns',
        price: 180,
        discountPrice: 149,
        mrp: 220,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/kaali-mirch.png'],
        stock: 120,
        isFeatured: true,
        weightOptions: [{ label: '100g', price: 79 }, { label: '250g', price: 149 }, { label: '500g', price: 280 }],
        rating: 4.8,
        numReviews: 45,
        tags: ['spices', 'pepper', 'whole-spices', 'essential'],
        soldCount: 850,
        isActive: true,
      },
      {
        name: 'Sabut Long (Cloves)',
        slug: 'sabut-long-cloves',
        description: 'Highly aromatic, handpicked cloves (laung). Perfect for adding spicy warmth to beverages, curries, and traditional medicines.',
        shortDescription: 'Fragrant and pure whole cloves',
        price: 250,
        discountPrice: 199,
        mrp: 280,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/long-cloves.png'],
        stock: 80,
        isFeatured: true,
        weightOptions: [{ label: '50g', price: 110 }, { label: '100g', price: 199 }, { label: '250g', price: 470 }],
        rating: 4.7,
        numReviews: 32,
        tags: ['spices', 'cloves', 'laung', 'whole-spices'],
        soldCount: 520,
        isActive: true,
      },
      {
        name: 'Sabut Jeera (Cumin Seeds)',
        slug: 'sabut-jeera-cumin',
        description: 'Earthy and aromatic whole cumin seeds. Sourced from Rajasthan, ideal for daily tempering (tadka) and enhancing the flavor of Indian dishes.',
        shortDescription: 'Aromatic Rajasthan whole cumin seeds',
        price: 120,
        discountPrice: 99,
        mrp: 140,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/jeera.png'],
        stock: 150,
        isFeatured: true,
        weightOptions: [{ label: '250g', price: 99 }, { label: '500g', price: 185 }, { label: '1kg', price: 350 }],
        rating: 4.6,
        numReviews: 68,
        tags: ['spices', 'cumin', 'jeera', 'whole-spices', 'popular'],
        soldCount: 1200,
        isActive: true,
      },
      {
        name: 'Sabut Dalchini (Cinnamon Sticks)',
        slug: 'sabut-dalchini-cinnamon',
        description: 'Sweet and woody Ceylon cinnamon sticks. Hand-harvested and dried to retain their rich aroma and natural flavor.',
        shortDescription: 'Premium Ceylon cinnamon sticks',
        price: 199,
        discountPrice: 159,
        mrp: 240,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/dal-chini.png'],
        stock: 90,
        isFeatured: false,
        weightOptions: [{ label: '100g', price: 159 }, { label: '250g', price: 340 }],
        rating: 4.5,
        numReviews: 24,
        tags: ['spices', 'cinnamon', 'dalchini', 'whole-spices'],
        soldCount: 430,
        isActive: true,
      },
      {
        name: 'Sabut Elaichi (Green Cardamom)',
        slug: 'sabut-elaichi-cardamom',
        description: 'Aromatic green cardamom pods from the pristine hills of Idukki, Kerala. Known for their intense floral aroma and sweet taste.',
        shortDescription: 'Premium green cardamom from Kerala hills',
        price: 800,
        discountPrice: 699,
        mrp: 950,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/elaichi.jpg'],
        stock: 75,
        isFeatured: true,
        weightOptions: [{ label: '50g', price: 150 }, { label: '100g', price: 299 }, { label: '250g', price: 699 }],
        rating: 4.9,
        numReviews: 87,
        tags: ['spices', 'cardamom', 'elaichi', 'premium', 'popular'],
        soldCount: 950,
        isActive: true,
      },
      {
        name: 'Sabut Badi Elaichi (Black Cardamom)',
        slug: 'sabut-badi-elaichi-black-cardamom',
        description: 'Smoky and rich black cardamom pods. Essential for authentic biryanis, slow-cooked curries, and spice blends.',
        shortDescription: 'Earthy and smoky black cardamom pods',
        price: 350,
        discountPrice: 299,
        mrp: 380,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/badi-elaichi.jpg'],
        stock: 60,
        weightOptions: [{ label: '100g', price: 299 }, { label: '250g', price: 690 }],
        rating: 4.6,
        numReviews: 18,
        tags: ['spices', 'black-cardamom', 'badi-elaichi'],
        soldCount: 210,
        isActive: true,
      },
      {
        name: 'Tez Patta (Bay Leaves)',
        slug: 'tez-patta-bay-leaves',
        description: 'Premium quality aromatic dried bay leaves. A staple in Indian curries, rice preparations, and slow-cooked stews.',
        shortDescription: 'Fragrant and dried Indian bay leaves',
        price: 60,
        discountPrice: 49,
        mrp: 80,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/tez-patta.jpg'],
        stock: 200,
        weightOptions: [{ label: '50g', price: 49 }, { label: '100g', price: 89 }],
        rating: 4.4,
        numReviews: 29,
        tags: ['spices', 'bay-leaves', 'tez-patta'],
        soldCount: 310,
        isActive: true,
      },
      {
        name: 'Sabut Dhaniya (Coriander Seeds)',
        slug: 'sabut-dhaniya-seeds',
        description: 'Fresh and citrusy whole coriander seeds. Ideal for roasting, grinding fresh spice powder, or using in traditional pickles and stews.',
        shortDescription: 'Premium whole coriander seeds',
        price: 90,
        discountPrice: 69,
        mrp: 110,
        categoryId: catMap['whole-spices'],
        images: ['/uploads/sabut-dhaniya.jpg'],
        stock: 140,
        weightOptions: [{ label: '250g', price: 69 }, { label: '500g', price: 130 }, { label: '1kg', price: 240 }],
        rating: 4.5,
        numReviews: 38,
        tags: ['spices', 'coriander', 'dhaniya'],
        soldCount: 420,
        isActive: true,
      },

      // --- DRY FRUITS ---
      {
        name: 'Almonds (Badam) Premium',
        slug: 'almonds-badam-premium',
        description: 'Premium California almonds. Large, crunchy, and packed with nutrients, vitamin E, and healthy fats. Great for daily energy.',
        shortDescription: 'Premium California almonds - large & crunchy',
        price: 900,
        discountPrice: 799,
        mrp: 1100,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/badam.jpg'],
        stock: 180,
        isFeatured: true,
        weightOptions: [{ label: '250g', price: 220 }, { label: '500g', price: 420 }, { label: '1kg', price: 799 }],
        rating: 4.8,
        numReviews: 125,
        tags: ['dry-fruits', 'almonds', 'badam', 'healthy', 'popular'],
        soldCount: 2200,
        isActive: true,
      },
      {
        name: 'Cashew Nuts (Kaju) Premium',
        slug: 'cashew-nuts-kaju-premium',
        description: 'Premium Goa cashew nuts. Large, sweet, and perfectly white. Sourced from the finest farms, great for snacking and cooking.',
        shortDescription: 'Premium W180 whole cashew nuts',
        price: 850,
        discountPrice: 749,
        mrp: 1000,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/kaju.jpg'],
        stock: 150,
        isFeatured: true,
        weightOptions: [{ label: '250g', price: 210 }, { label: '500g', price: 400 }, { label: '1kg', price: 749 }],
        rating: 4.7,
        numReviews: 94,
        tags: ['dry-fruits', 'cashews', 'kaju', 'rich', 'popular'],
        soldCount: 1850,
        isActive: true,
      },
      {
        name: 'Pistachios (Pista) Roasted & Salted',
        slug: 'pistachios-pista-salted',
        description: 'Crunchy and delicious roasted pistachios with a touch of salt. Perfectly split shells, rich in protein and fiber.',
        shortDescription: 'Premium roasted & salted pistachios',
        price: 950,
        discountPrice: 849,
        mrp: 1200,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/pista.jpg'],
        stock: 110,
        isFeatured: false,
        weightOptions: [{ label: '250g', price: 230 }, { label: '500g', price: 450 }, { label: '1kg', price: 849 }],
        rating: 4.6,
        numReviews: 61,
        tags: ['dry-fruits', 'pistachios', 'pista', 'snacks'],
        soldCount: 930,
        isActive: true,
      },
      {
        name: 'Raisins (Kishmish) Premium Green',
        slug: 'raisins-kishmish-green',
        description: 'Naturally sun-dried premium green raisins. Sweet, juicy, and seedless. A great addition to desserts or for daily consumption.',
        shortDescription: 'Sweet and juicy green seedless raisins',
        price: 280,
        discountPrice: 249,
        mrp: 350,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/kishmish.jpg'],
        stock: 130,
        weightOptions: [{ label: '250g', price: 75 }, { label: '500g', price: 135 }, { label: '1kg', price: 249 }],
        rating: 4.5,
        numReviews: 42,
        tags: ['dry-fruits', 'raisins', 'kishmish'],
        soldCount: 650,
        isActive: true,
      },
      {
        name: 'Walnuts (Akhrot) Kernels',
        slug: 'walnuts-akhrot-kernels',
        description: 'Premium light-colored walnut kernels. Rich in Omega-3 fatty acids and antioxidants. Excellent for brain health and snacking.',
        shortDescription: 'Premium raw walnut halves (Akhrot)',
        price: 1100,
        discountPrice: 949,
        mrp: 1300,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/akhrot.jpg'],
        stock: 95,
        isFeatured: true,
        weightOptions: [{ label: '250g', price: 260 }, { label: '500g', price: 499 }, { label: '1kg', price: 949 }],
        rating: 4.7,
        numReviews: 53,
        tags: ['dry-fruits', 'walnuts', 'akhrot', 'brain-health'],
        soldCount: 880,
        isActive: true,
      },
      {
        name: 'Dried Figs (Anjeer) Premium',
        slug: 'dried-figs-anjeer-premium',
        description: 'Sweet and soft dried figs (Anjeer). Naturally sweet and highly fibrous, these are excellent healthy snacks and immunity boosters.',
        shortDescription: 'Naturally sweet and soft dried figs',
        price: 450,
        discountPrice: 399,
        mrp: 550,
        categoryId: catMap['dry-fruits'],
        images: ['/uploads/anjeer.jpg'],
        stock: 70,
        weightOptions: [{ label: '250g', price: 220 }, { label: '500g', price: 399 }],
        rating: 4.6,
        numReviews: 31,
        tags: ['dry-fruits', 'figs', 'anjeer'],
        soldCount: 420,
        isActive: true,
      },

      // --- POOJA SAMAGRI ---
      {
        name: 'Bhimseni Pure Kapoor (Camphor)',
        slug: 'bhimseni-pure-kapoor-camphor',
        description: '100% pure Bhimseni camphor crystals. Free from paraffin or adulterants. Leaves a soothing aroma and clean smoke during prayers.',
        shortDescription: '100% Pure Bhimseni Camphor crystals',
        price: 180,
        discountPrice: 149,
        mrp: 200,
        categoryId: catMap['pooja-items'],
        images: ['/uploads/kapoor.jpg'],
        stock: 120,
        isFeatured: true,
        weightOptions: [{ label: '100g', price: 149 }, { label: '250g', price: 340 }],
        rating: 4.8,
        numReviews: 76,
        tags: ['pooja', 'camphor', 'kapoor', 'essential'],
        soldCount: 1150,
        isActive: true,
      },
      {
        name: 'Pure Chandan (Sandalwood) Powder',
        slug: 'pure-chandan-sandalwood-powder',
        description: 'Authentic yellow sandalwood powder. Ideal for making tilak or offering to deities during rituals. Extremely cool and aromatic.',
        shortDescription: 'Pure fragrant yellow sandalwood powder',
        price: 120,
        discountPrice: 99,
        mrp: 150,
        categoryId: catMap['pooja-items'],
        images: ['/uploads/chandan.jpg'],
        stock: 110,
        weightOptions: [{ label: '50g', price: 99 }, { label: '100g', price: 180 }],
        rating: 4.6,
        numReviews: 35,
        tags: ['pooja', 'chandan', 'sandalwood'],
        soldCount: 540,
        isActive: true,
      },
      {
        name: 'Cotton Rui Batti (Diya Wicks)',
        slug: 'cotton-rui-batti-diya-wicks',
        description: 'Premium quality handmade cotton wicks for diya lamps. Available in both round (gol) and long variants. Ensures steady and smoke-free burning.',
        shortDescription: 'Handmade pure cotton diya wicks',
        price: 50,
        discountPrice: 39,
        mrp: 60,
        categoryId: catMap['pooja-items'],
        images: ['/uploads/rui-batti.jpg'],
        stock: 250,
        weightOptions: [{ label: 'Gol Batti (Pack of 100)', price: 39 }, { label: 'Lambi Batti (Pack of 100)', price: 39 }],
        rating: 4.5,
        numReviews: 19,
        tags: ['pooja', 'wicks', 'batti', 'cotton'],
        soldCount: 620,
        isActive: true,
      },
    ]);
    console.log(`${products.length} products created`);

    await SiteSetting.bulkCreate([
      {
        key: 'site_info',
        value: {
          siteName: 'Pandit Ji Masale',
          tagline: 'Shudhta Aapke Ghar Tak',
          email: 'hmudgal577@gmail.com',
          phone: '+917415992703',
          address: 'Birla Nagar, Gwalior, Madhya Pradesh - 474004',
          workingHours: 'Mon-Sun: 9:00 AM - 9:00 PM',
        },
      },
      {
        key: 'delivery_charges',
        value: {
          standard: 40,
          freeAbove: 499,
          express: 99,
        },
      },
      {
        key: 'gst',
        value: {
          rate: 0.05,
          label: 'GST (5%)',
        },
      },
      {
        key: 'social_links',
        value: {
          facebook: 'https://facebook.com/panditjimasale',
          instagram: 'https://instagram.com/panditjimasale',
          twitter: 'https://twitter.com/panditjimasale',
          youtube: 'https://youtube.com/@panditjimasale',
        },
      },
      {
        key: 'hero_banners',
        value: [
          { title: 'Pure & Natural Spices', subtitle: 'Authentic Whole Spices for Aroma & Flavor', buttonText: 'Shop Now', link: '/shop?category=whole-spices', bgColor: '#7A1E1E' },
          { title: 'Premium Dry Fruits', subtitle: 'Direct from farms to your home', buttonText: 'Explore', link: '/shop?category=dry-fruits', bgColor: '#E8862A' },
          { title: 'Complete Pooja Samagri', subtitle: 'Purity guaranteed for all your spiritual needs', buttonText: 'View Range', link: '/shop?category=pooja-items', bgColor: '#2B1B12' },
        ],
      },
    ]);
    console.log('Site settings created');
    console.log('\n--- Seed Complete ---');
    console.log('Admin: admin@panditji.com / admin123');
    console.log('Customer: rahul@example.com / customer123');

    console.log('Seed completed successfully!');
  } catch (error) {
    console.error('Seed error:', error);
    throw error;
  }
};

// Run directly if called from command line
if (require.main === module) {
  seed().then(() => process.exit(0)).catch(() => process.exit(1));
}

module.exports = seed;
